#pragma once

// Generated by mamec
//   Format Version: 1
//   First Code      : 'F' (0x46)
//   Last Code       : 'F' (0x46)
//   Font Height     : 8 px
//   Max Glyph Width : 8 px
//   Total Pixels    : 64 px
//   Fragment Shape  : Vertical
//   Bit Order       : MSB First
//   Large Font      : No
//   Proportional    : No
//   Ext. Header     : No
//   Estimated Footprint:
//     Header        :    8 Bytes
//     Glyph Table   :    2 Bytes (  2.00 Bytes/glyph)
//     Frag. Table   :    2 Bytes (  3.12% used)
//     Bytecodes     :    4 Bytes (  4.00 Bytes/glyph)
//     Total         :   16 Bytes ( 16.00 Bytes/glyph)
//   Compression Performance:
//     LUD   :    2 -->    1 (-12.50%)
//     LUP   :    1 -->    1 (  0.00%)
//     RPT   :    4 -->    1 (-37.50%)
//     XOR   :    1 -->    1 (  0.00%)
//     Total :    8 -->    4 (-50.00%)
//   Memory Efficiency:  4.000 px/Byte

#include <stdint.h>

#ifdef MAMEFONT_USE_PROGMEM
#include <avr/pgmspace.h>
#endif

#ifndef MAMEFONT_PROGMEM
#ifdef PROGMEM
#define MAMEFONT_PROGMEM PROGMEM
#else
#define MAMEFONT_PROGMEM
#endif
#define MAMEFONT_PROGMEM_SELF_DEFINED
#endif

const uint8_t TestF_s08w02_blob[] MAMEFONT_PROGMEM = {
  // Font Header
  0x01, 0xC0, 0x46, 0x46, 0x00, 0x07, 0x07, 0x20,
  // Glyph Table
  0x00, 0xFF,
  // Fragment Table
  0xFF, 0xCC,
  // Byte Code Block
  0xC0, 0x81, 0xE3, 0xFA
};

#ifdef MAMEFONT_PROGMEM_SELF_DEFINED
#undef MAMEFONT_PROGMEM
#endif
