#pragma once

// Generated by mamec
//   Format Version: 1
//   First Code      : ' ' (0x20)
//   Last Code       : ' ' (0x20)
//   Font Height     : 1 px
//   Max Glyph Width : 1 px
//   Total Pixels    : 1 px
//   Fragment Shape  : Vertical
//   Bit Order       : LSB First
//   Large Font      : No
//   Proportional    : No
//   Ext. Header     : No
//   Estimated Footprint:
//     Header        :    8 Bytes
//     Glyph Table   :    2 Bytes (  2.00 Bytes/glyph)
//     Frag. Table   :    2 Bytes (  3.12% used)
//     Byte Codes    :    4 Bytes (  4.00 Bytes/glyph)
//     Total         :   16 Bytes ( 16.00 Bytes/glyph)
//   Instruction Performance:
//     RPT   :    1 -->    1 (  0.00%)
//     Total :    1 -->    1 (  0.00%)
//   Byte Code References:
//     Multiple References :   0 Bytes
//     No Ref (ABO)        :   3 Bytes
//     No Ref (Unexpected) :   0 Bytes
//   Memory Efficiency:  0.062 px/Byte

#include <stdint.h>

#ifdef MAMEFONT_USE_PROGMEM
#include <avr/pgmspace.h>
#endif

#ifndef MAMEFONT_PROGMEM
#ifdef PROGMEM
#define MAMEFONT_PROGMEM PROGMEM
#else
#define MAMEFONT_PROGMEM
#endif
#define MAMEFONT_PROGMEM_SELF_DEFINED
#endif

const uint8_t Empty_s01_blob[] MAMEFONT_PROGMEM = {
  // Font Header
  0x01, 0x80, 0x20, 0x20, 0x00, 0x00, 0x00, 0x10,
  // Glyph Table
  0x00, 0xFF,
  // Fragment Table
  0x00, 0x00,
  // Byte Code Block
  0xE0, 0xFF, 0xFF, 0xFF
};

#ifdef MAMEFONT_PROGMEM_SELF_DEFINED
#undef MAMEFONT_PROGMEM
#endif
