#pragma once

// Generated by mamec
//   Format Version: 1
//   First Code      : 'F' (0x46)
//   Last Code       : 'F' (0x46)
//   Font Height     : 16 px
//   Max Glyph Width : 16 px
//   Total Pixels    : 256 px
//   Fragment Shape  : Vertical
//   Bit Order       : LSB First
//   Large Font      : No
//   Proportional    : No
//   Ext. Header     : No
//   Estimated Footprint:
//     Header        :    8 Bytes
//     Glyph Table   :    2 Bytes (  2.00 Bytes/glyph)
//     Frag. Table   :    2 Bytes (  3.12% used)
//     Byte Codes    :   11 Bytes ( 11.00 Bytes/glyph)
//     Total         :   23 Bytes ( 23.00 Bytes/glyph)
//   Instruction Performance:
//     CPY   :   11 -->    2 (-28.12%)
//     LUP   :    1 -->    1 (  0.00%)
//     RPT   :   17 -->    3 (-43.75%)
//     SFT   :    3 -->    2 (- 3.12%)
//     Total :   32 -->    8 (-75.00%)
//   Byte Code References:
//     Multiple References :   0 Bytes
//     No Ref (ABO)        :   3 Bytes
//     No Ref (Unexpected) :   0 Bytes
//   Memory Efficiency: 11.130 px/Byte

#include <stdint.h>

#ifdef MAMEFONT_USE_PROGMEM
#include <avr/pgmspace.h>
#endif

#ifndef MAMEFONT_PROGMEM
#ifdef PROGMEM
#define MAMEFONT_PROGMEM PROGMEM
#else
#define MAMEFONT_PROGMEM
#endif
#define MAMEFONT_PROGMEM_SELF_DEFINED
#endif

const uint8_t TestF_s16w04_blob[] MAMEFONT_PROGMEM = {
  // Font Header
  0x01, 0x80, 0x46, 0x46, 0x00, 0x0F, 0x0F, 0x40,
  // Glyph Table
  0x00, 0xFF,
  // Fragment Table
  0xFF, 0x00,
  // Byte Code Block
  0x80, 0xE2, 0x2C, 0xE4, 0x67, 0x62, 0xE8, 0x2D, 0xFF, 0xFF, 0xFF
};

#ifdef MAMEFONT_PROGMEM_SELF_DEFINED
#undef MAMEFONT_PROGMEM
#endif
