// Generated by MameFont
//   Format Version: 1
//   First Code      : 70
//   Glyph Count     : 1
//   Font Height     : 16 px
//   Max Glyph Width : 16 px
//   Total Pixels    : 256 px
//   Fragment Shape  : Vertical
//   Bit Order       : LSB First
//   Shrinked Format : Yes
//   Estimated Footprint:
//     Header        :    8 Bytes
//     Glyph Table   :    2 Bytes (2 Bytes/glyph)
//     Lookup Table  :    2 Bytes (3.12% used)
//     Bytecodes     :   11 Bytes (11.00 Bytes/glyph)
//     Total         :   23 Bytes (23.00 Bytes/glyph)
//   Compression Performance:
//     CPY         :   14 -->    2 ( -37.50%)
//     LUP         :    1 -->    1 (  +0.00%)
//     RPT         :   14 -->    3 ( -34.38%)
//     SFT         :    3 -->    2 (  -3.12%)
//     Total       :   32 -->    8 ( -75.00%)
//   Memory Efficiency: 11.130 px/Byte

#include <stdint.h>
#include <mamefont/mamefont.hpp>

#ifdef MAMEFONT_USE_PROGMEM
#include <avr/pgmspace.h>
#define MAMEFONT_PROGMEM PROGMEM
#else
#define MAMEFONT_PROGMEM
#endif

const uint8_t TestF_s16w04_blob[] MAMEFONT_PROGMEM = {
  // Font Header
  0x01, 0xA0, 0x46, 0x00, 0x01, 0x0F, 0x04, 0x0F,
  // Glyph Table
  0x00, 0x1F,
  // Lookup Table
  0xFF, 0x00,
  // Bytecodes
  0x80, 0xE2, 0x2C, 0xE4, 0x67, 0x65, 0xE5, 0x2D, 0xFF, 0xFF, 0xFF,
};

extern const mamefont::Font TestF_s16w04(TestF_s16w04_blob);

#undef MAMEFONT_PROGMEM
