#pragma once

// Generated by mamec
//   Format Version: 0
//   First Code      : 'F' (0x46)
//   Last Code       : 'F' (0x46)
//   Max Glyph Width : 8 px
//   Font Height     : 8 px
//   Total Pixels    : 64 px
//   Fragment Shape  : Horizontal
//   Pixel Order     : Near Pixel First
//   Pixel Format    : 1 bpp
//   Large Font      : No
//   Proportional    : No
//   Ext. Header     : No
//   Estimated Footprint:
//     Header        :   12 Bytes
//     Glyph Table   :    2 Bytes (  2.00 Bytes/glyph)
//     Frag. Table   :    4 Bytes (  6.25% used)
//     Byte Codes    :    7 Bytes (  7.00 Bytes/glyph)
//     Total         :   25 Bytes ( 25.00 Bytes/glyph)
//   Instruction Performance:
//     CPY   :    3 -->    1 (-25.00%)
//     LUD   :    4 -->    2 (-25.00%)
//     LUP   :    1 -->    1 (  0.00%)
//     Total :    8 -->    4 (-50.00%)
//   Byte Code References:
//     Multiple References :   0 Bytes
//     No Ref (ABO)        :   3 Bytes
//     No Ref (Unexpected) :   0 Bytes
//   Memory Efficiency:  2.560 px/Byte

#include <stdint.h>

#ifdef MAMEFONT_USE_PROGMEM
#include <avr/pgmspace.h>
#endif

#ifndef MAMEFONT_PROGMEM
#ifdef PROGMEM
#define MAMEFONT_PROGMEM PROGMEM
#else
#define MAMEFONT_PROGMEM
#endif
#define MAMEFONT_PROGMEM_SELF_DEFINED
#endif

const uint8_t TestF_s08w02_blob[] MAMEFONT_PROGMEM = {
  // Font Header
  0x00, 0x00, 0x46, 0x46, 0x07, 0x07, 0x21, 0x02, 0x00, 0x00, 0x07, 0x01,
  // Glyph Table
  0x00, 0xFF,
  // Fragment Table
  0xFF, 0x03, 0x7F, 0x00,
  // Byte Code Block
  0xC0, 0xC1, 0x82, 0x62, 0xFF, 0xFF, 0xFF
};

#ifdef MAMEFONT_PROGMEM_SELF_DEFINED
#undef MAMEFONT_PROGMEM
#endif
