// Generated by MameFont
//   Format Version: 1
//   First Code      : 70
//   Glyph Count     : 1
//   Font Height     : 16 px
//   Max Glyph Width : 16 px
//   Total Pixels    : 256 px
//   Fragment Shape  : Horizontal
//   Bit Order       : LSB First
//   Shrinked Format : Yes
//   Estimated Footprint:
//     Header        :    8 Bytes
//     Glyph Table   :    2 Bytes (2 Bytes/glyph)
//     Lookup Table  :    2 Bytes (3.12% used)
//     Bytecodes     :   13 Bytes (13.00 Bytes/glyph)
//     Total         :   25 Bytes (25.00 Bytes/glyph)
//   Compression Performance:
//     CPX         :    8 -->    3 ( -15.62%)
//     CPY         :   14 -->    2 ( -37.50%)
//     LUD (step=0):    2 -->    1 (  -3.12%)
//     LUP         :    1 -->    1 (  +0.00%)
//     RPT         :    6 -->    2 ( -12.50%)
//     SFT         :    1 -->    1 (  +0.00%)
//     Total       :   32 -->   10 ( -68.75%)
//   Memory Efficiency: 10.240 px/Byte

#include <stdint.h>
#include <mamefont/mamefont.hpp>

#ifdef MAMEFONT_USE_PROGMEM
#include <avr/pgmspace.h>
#define MAMEFONT_PROGMEM PROGMEM
#else
#define MAMEFONT_PROGMEM
#endif

const uint8_t TestF_s16w04_blob[] MAMEFONT_PROGMEM = {
  // Font Header
  0x01, 0x20, 0x46, 0x00, 0x01, 0x0F, 0x04, 0x0F,
  // Glyph Table
  0x00, 0x1F,
  // Lookup Table
  0xFF, 0x3F,
  // Bytecodes
  0x80, 0xE2, 0x2C, 0xE2, 0x47, 0x40, 0x14, 0x06, 0xC1, 0x65, 0xFF, 0xFF, 0xFF,
};

extern const mamefont::Font TestF_s16w04(TestF_s16w04_blob);

#undef MAMEFONT_PROGMEM
