#pragma once

// Generated by mamec
//   Format Version: 1
//   First Code      : 'F' (0x46)
//   Last Code       : 'F' (0x46)
//   Font Height     : 8 px
//   Max Glyph Width : 8 px
//   Total Pixels    : 64 px
//   Fragment Shape  : Horizontal
//   Bit Order       : LSB First
//   Large Font      : No
//   Proportional    : No
//   Ext. Header     : No
//   Estimated Footprint:
//     Header        :    8 Bytes
//     Glyph Table   :    2 Bytes (  2.00 Bytes/glyph)
//     Frag. Table   :    4 Bytes (  6.25% used)
//     Bytecodes     :    4 Bytes (  4.00 Bytes/glyph)
//     Total         :   18 Bytes ( 18.00 Bytes/glyph)
//   Compression Performance:
//     CPY   :    3 -->    1 (-25.00%)
//     LUD   :    4 -->    2 (-25.00%)
//     LUP   :    1 -->    1 (  0.00%)
//     Total :    8 -->    4 (-50.00%)
//   Memory Efficiency:  3.556 px/Byte

#include <stdint.h>

#ifdef MAMEFONT_USE_PROGMEM
#include <avr/pgmspace.h>
#endif

#ifndef MAMEFONT_PROGMEM
#ifdef PROGMEM
#define MAMEFONT_PROGMEM PROGMEM
#else
#define MAMEFONT_PROGMEM
#endif
#define MAMEFONT_PROGMEM_SELF_DEFINED
#endif

const uint8_t TestF_s08w02_blob[] MAMEFONT_PROGMEM = {
  // Font Header
  0x01, 0x00, 0x46, 0x46, 0x01, 0x07, 0x07, 0x20,
  // Glyph Table
  0x00, 0xFF,
  // Fragment Table
  0xFF, 0x03, 0x7F, 0x00,
  // Byte Code Block
  0xC0, 0xC1, 0x82, 0x62
};

#ifdef MAMEFONT_PROGMEM_SELF_DEFINED
#undef MAMEFONT_PROGMEM
#endif
