#pragma once

// Generated by mamec
//   Format Version: 1
//   First Code      : 'F' (0x46)
//   Last Code       : 'F' (0x46)
//   Font Height     : 16 px
//   Max Glyph Width : 16 px
//   Total Pixels    : 256 px
//   Fragment Shape  : Horizontal
//   Bit Order       : LSB First
//   Large Font      : No
//   Proportional    : No
//   Ext. Header     : No
//   Estimated Footprint:
//     Header        :    8 Bytes
//     Glyph Table   :    2 Bytes (  2.00 Bytes/glyph)
//     Frag. Table   :    4 Bytes (  6.25% used)
//     Bytecodes     :   10 Bytes ( 10.00 Bytes/glyph)
//     Total         :   24 Bytes ( 24.00 Bytes/glyph)
//   Compression Performance:
//     CPY   :   18 -->    3 (-46.88%)
//     LUD   :    2 -->    1 (- 3.12%)
//     LUP   :    2 -->    2 (  0.00%)
//     RPT   :    9 -->    3 (-18.75%)
//     SFT   :    1 -->    1 (  0.00%)
//     Total :   32 -->   10 (-68.75%)
//   Memory Efficiency: 10.667 px/Byte

#include <stdint.h>

#ifdef MAMEFONT_USE_PROGMEM
#include <avr/pgmspace.h>
#endif

#ifndef MAMEFONT_PROGMEM
#ifdef PROGMEM
#define MAMEFONT_PROGMEM PROGMEM
#else
#define MAMEFONT_PROGMEM
#endif
#define MAMEFONT_PROGMEM_SELF_DEFINED
#endif

const uint8_t TestF_s16w04_blob[] MAMEFONT_PROGMEM = {
  // Font Header
  0x01, 0x00, 0x46, 0x46, 0x01, 0x0F, 0x0F, 0x40,
  // Glyph Table
  0x00, 0xFF,
  // Fragment Table
  0x3F, 0xFF, 0x00, 0x00,
  // Byte Code Block
  0x81, 0xE2, 0x2C, 0xE2, 0x5C, 0x4E, 0x82, 0xE2, 0xC0, 0x65
};

#ifdef MAMEFONT_PROGMEM_SELF_DEFINED
#undef MAMEFONT_PROGMEM
#endif
