// Generated by MameFont
//   Format Version: 1
//   First Code      : 70
//   Glyph Count     : 1
//   Font Height     : 8 px
//   Max Glyph Width : 8 px
//   Total Pixels    : 64 px
//   Fragment Shape  : Vertical
//   Bit Order       : MSB First
//   Shrinked Format : Yes
//   Estimated Footprint:
//     Header        :    8 Bytes
//     Glyph Table   :    2 Bytes (2 Bytes/glyph)
//     Lookup Table  :    2 Bytes (3.12% used)
//     Bytecodes     :    7 Bytes (7.00 Bytes/glyph)
//     Total         :   19 Bytes (19.00 Bytes/glyph)
//   Compression Performance:
//     LUD (step=0):    2 -->    1 ( -12.50%)
//     LUP         :    1 -->    1 (  +0.00%)
//     RPT         :    4 -->    1 ( -37.50%)
//     SFT         :    1 -->    1 (  +0.00%)
//     Total       :    8 -->    4 ( -50.00%)
//   Memory Efficiency:  3.368 px/Byte

#include <stdint.h>
#include <mamefont/mamefont.hpp>

#ifdef MAMEFONT_USE_PROGMEM
#include <avr/pgmspace.h>
#define MAMEFONT_PROGMEM PROGMEM
#else
#define MAMEFONT_PROGMEM
#endif

const uint8_t TestF_s08w02_blob[] MAMEFONT_PROGMEM = {
  // Font Header
  0x01, 0xE0, 0x46, 0x00, 0x01, 0x07, 0x09, 0x07,
  // Glyph Table
  0x00, 0x87,
  // Lookup Table
  0xFF, 0xCC,
  // Bytecodes
  0xC0, 0x81, 0xE3, 0x0C, 0xFF, 0xFF, 0xFF,
};

extern const mamefont::Font TestF_s08w02(TestF_s08w02_blob);

#undef MAMEFONT_PROGMEM
