// Generated by MameFont
//   Format Version: 1
//   First Code      : 70
//   Glyph Count     : 1
//   Font Height     : 16 px
//   Max Glyph Width : 16 px
//   Total Pixels    : 256 px
//   Fragment Shape  : Horizontal
//   Bit Order       : MSB First
//   Shrinked Format : No
//   Estimated Footprint:
//     Header        :    8 Bytes
//     Glyph Table   :    4 Bytes (4 Bytes/glyph)
//     Lookup Table  :    4 Bytes (6.25% used)
//     Bytecodes     :   13 Bytes (13.00 Bytes/glyph)
//     Total         :   29 Bytes (29.00 Bytes/glyph)
//   Compression Performance:
//     CPY         :   18 -->    3 ( -46.88%)
//     LUD (step=0):    2 -->    1 (  -3.12%)
//     LUP         :    2 -->    2 (  +0.00%)
//     RPT         :    9 -->    3 ( -18.75%)
//     SFT         :    1 -->    1 (  +0.00%)
//     Total       :   32 -->   10 ( -68.75%)
//   Memory Efficiency:  8.828 px/Byte

#include <stdint.h>
#include <mamefont/mamefont.hpp>

#ifdef MAMEFONT_USE_PROGMEM
#include <avr/pgmspace.h>
#define MAMEFONT_PROGMEM PROGMEM
#else
#define MAMEFONT_PROGMEM
#endif

const uint8_t TestF_s16w4_blob[] MAMEFONT_PROGMEM = {
  // Font Header
  0x01, 0x40, 0x46, 0x00, 0x03, 0x0F, 0x13, 0x0F,
  // Glyph Table
  0x00, 0x00, 0x0F, 0x11,
  // Lookup Table
  0xFF, 0x00, 0xFC, 0x00,
  // Bytecodes
  0x00, 0x62, 0x8C, 0x62, 0xDC, 0xCE, 0x01, 0x62, 0x42, 0xE5, 0xF0, 0xF0, 0xF0,
};

extern const mamefont::Font TestF_s16w4(TestF_s16w4_blob);

#undef MAMEFONT_PROGMEM
