// Generated by MameFont
//   Format Version: 1
//   First Code      : 70
//   Glyph Count     : 1
//   Font Height     : 8 px
//   Max Glyph Width : 8 px
//   Total Pixels    : 64 px
//   Fragment Shape  : Horizontal
//   Bit Order       : LSB First
//   Shrinked Format : Yes
//   Estimated Footprint:
//     Header        :    8 Bytes
//     Glyph Table   :    2 Bytes (2 Bytes/glyph)
//     Lookup Table  :    4 Bytes (6.25% used)
//     Bytecodes     :    7 Bytes (7.00 Bytes/glyph)
//     Total         :   21 Bytes (21.00 Bytes/glyph)
//   Compression Performance:
//     CPY         :    3 -->    1 ( -25.00%)
//     LUD (step=0):    4 -->    2 ( -25.00%)
//     LUP         :    1 -->    1 (  +0.00%)
//     Total       :    8 -->    4 ( -50.00%)
//   Memory Efficiency:  3.048 px/Byte

#include <stdint.h>
#include <mamefont/mamefont.hpp>

#ifdef MAMEFONT_USE_PROGMEM
#include <avr/pgmspace.h>
#define MAMEFONT_PROGMEM PROGMEM
#else
#define MAMEFONT_PROGMEM
#endif

const uint8_t TestF_s8w2_blob[] MAMEFONT_PROGMEM = {
  // Font Header
  0x01, 0x20, 0x46, 0x00, 0x03, 0x07, 0x09, 0x07,
  // Glyph Table
  0x00, 0x87,
  // Lookup Table
  0xFF, 0x03, 0x7F, 0x00,
  // Bytecodes
  0xC0, 0xC1, 0x82, 0x62, 0xFF, 0xFF, 0xFF,
};

extern const mamefont::Font TestF_s8w2(TestF_s8w2_blob);

#undef MAMEFONT_PROGMEM
